version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"