version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
  
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      all-other-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"